### ISSUE TITLE
Swimming Competition To-Do List

### ISSUE THREAD

**Issue by youcatastrophe** [youcatastrophe/web-app__swimming-competition#1]
- [ ] Write a method that determines the top 3 results for each event.
- [ ] update erb files to show the associated conference every time a rookery (school) is referenced.
- [ ] Find new ways to improve user experience by adding more dynamic links to various objects.
